/* eslint-disable @next/next/no-page-custom-font */
import Header from '~/memory/widgets/header/facade/header';
import '../styles/global.css';
import TranslationsProvider from '~/memory/shared/providers/i18n-provider';
import initTranslations from 'apps/memory/i18n';
export const metadata = {
  title: 'Welcome to memory',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { resources } = await initTranslations(locale, ['common']);
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin={'anonymous'}
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Jua&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <TranslationsProvider
          locale={locale}
          namespaces={['common']}
          resources={resources}
        >
          <Header locale={locale} />
          <main>{children}</main>
        </TranslationsProvider>
      </body>
    </html>
  );
}
